[package]
name = "powerline"
version = "0.1.0"
authors = ["softprops <d.tangren@gmail.com>"]
description = "add superpowers to your shell prompt"
license = "MIT"

[dependencies]
clap  = "2.27"
term = "0.4"
regex = "0.2"
git2 = "0.6"